version: "3.9"
services:
  jackal-game-session-service:
    container_name: jackal-game-session-service
    build: .
    image: jackal-game-session-service
    ports:
      - "${PORT_EXTERNAL}:${PORT_INTERNAL}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT_INTERNAL}