server:
  host: "localhost"
  port: 8030
  servlet:
    session:
      timeout: 5s
connection:
  checker:
    delay-s: 10

enterprise:
  base_url: "http://localhost:8080/api"
  not_started_url: "/game/resolve-not-started"