package ru.rsreu.jackal.game.field.cells.action

enum class CellActionResultType {
    FINISHED,
    FINISHED_WITH_FIGHT,
    FINISHED_WITH_KILL,
    FINISHED_WITH_PIRATE_ACTION_SKIP,
    FINISHED_WITH_PIRATE_ACTION_SKIP_AND_FIGHT,
    IN_PROCESS_WITH_TELEPORT_ON_SHIP,
    DIRECTION_QUESTION,
    IN_PROCESS,
    IN_PROCESS_REPEAT_ACTION
}